Update local run command
Looks like the command for running the ManagedVM locally has changed to require specification of the app.yaml path rather than containing directory. Note that the [public ManagedVM docs](https://cloud.google.com/appengine/docs/managed-vms/sdk) appear to also be behind on this change.

This was the error I received:
```
gcloud preview app run .
ERROR: Directories are not supported [.].  You must provide explicit yaml files.
ERROR: (gcloud.preview.app.run) Errors occurred while parsing the App Engine app configuration.
```